sudo: required
services:
  - docker

before_install:
  - docker build -t gmkrtchyan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gmkrtchyan/react-test npm test -- --coverage

after_success:
  - docker build -t gmkrtchyan/multi-client ./client
  - docker build -t gmkrtchyan/multi-nginx ./nginx
  - docker build -t gmkrtchyan/multi-server ./server
  - docker build -t gmkrtchyan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gmkrtchyan/multi-client
  - docker push gmkrtchyan/multi-nginx
  - docker push gmkrtchyan/multi-server
  - docker push gmkrtchyan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: docker
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-1-914659533361
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY = AKIA5J5PU4IYVELRNV7F
  secret_access_key:
    secure: $AWS_SECRET_KEY = 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
